services:
  mmwave-visualizer:
    build: .
    container_name: mmwave_vis
    ports:
      - "5000:5000"
    environment:
      - MQTT_BROKER=192.168.1.XX  # Change to your Broker IP
      - MQTT_PORT=1883
      - MQTT_USERNAME=your_user
      - MQTT_PASSWORD=your_password
      - Z2M_BASE_TOPIC=zigbee2mqtt
    restart: unless-stopped